# -*- coding: utf-8 -*-
"""
Created on Mon Oct 14 16:08:46 2024

@author: rbala
"""

from oemof.tools import economics
from oemof import network, solph
import pandas as pd
import os
workdir = os.getcwd()
import matplotlib.image as mpimg
import numpy as np
from src.postprocessing.export_results import export_csv_region, grid_energy_map, export_csv
from src.preprocessing.files import read_input_files
from src .preprocessing.conversion import investment_parameter
import matplotlib
import matplotlib.colors as mcolors
try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None


# name = os.path.basename(__file__)
# name = name.replace(".py", "")
# my_path = os.path.abspath(os.path.dirname(__file__))
#%%

my_path = os.path.abspath(os.path.dirname(__file__))

energysystem = solph.EnergySystem()
energysystem.restore(my_path, os.path.join(workdir, 
                      'dumps', '2030_BS0001', 'Basic_example_zorro_1_2030_BS0001_005.dump'))
YEAR= 2030
model_ID = 'BS0001'
# model_name '_' years '_' variations '.dump'
#img_path = os.path.abspath(os.path.join(os.getcwd(), 
                     # 'figures','Thuringia_karte_mit_Landkreisen_dull.png'))
#img=mpimg.imread(img_path)
#plt.show()
sequences = read_input_files(folder_name = 'data/sequences', sub_folder_name=None)
scalars = read_input_files(folder_name = 'data/scalars', sub_folder_name=None)
#demand = load_profile_scaling(scalars,sequences, YEAR, region=False)
#demand = zorro_1_loadprofile_scaling(YEAR, new_profile=True)
epc_costs = investment_parameter(scalars, YEAR, model_ID)
results = energysystem.results["main"]
year = [2030,2040,2050]
sim_data = sim_data
csv=export_csv(results, 2030, '2030_BS0001', 'Basic_example_zorro_1_2030_BS0001', '005', sim_data)
#export = export_csv_region(results, 2030 , '2030_BS0001', 'BS_regionalization_2030_BS0001')
#grid_energy_map(results,'2030_BS0001', 'BS_regionalization_2030_BS0001')

b_el = solph.views.node(results, 'Electricity')
b_gas = solph.views.node(results, 'Gas')
b_oil = solph.views.node(results, 'Oil_fuel')
b_bio = solph.views.node(results, 'Biomass')
b_bioWood = solph.views.node(results, 'BioWood')
b_solidf = solph.views.node(results, 'Solidfuel')
b_dist_heat = solph.views.node(results, 'District heating')
b_H2 = solph.views.node(results, 'Hydrogen')
#Syntbus = solph.views.node(results, 'Synthetische_Kraftstoffe')
Battery = solph.views.node(results, 'Battery')
Heat_storage = solph.views.node(results, 'Heat storage')
Pumped_hydro_storage = solph.views.node(results, 'Pumped_hydro_storage')
Gas_storage = solph.views.node(results, 'Gas_storage')
H2_storage = solph.views.node(results, 'H2_storage')
    



    



#%%
from mdutils.mdutils import MdUtils
from mdutils import Html
import os

permutation = '2030_BS0001'
scenario_num = '006'

hypothese = "Influence of an addtional Hydrogen import and a new component to produce synthetic fuel from Biomass"
sim_remarks = "- New hydrogen import block with variable cost (grid usage cost, production and transportation cost) \n- Biomass to liquid component to produce syn. fuel"
                
md_PATH = os.path.abspath(os.path.join(os.getcwd(), "docs", "scenario"))
img_PATH = os.path.abspath(os.path.join(os.getcwd(), "figures", str(permutation)))
YEAR, model_ID = permutation.split("_")

       
mdFile = MdUtils(file_name=  os.path.join(md_PATH, str(permutation) + '_' +scenario_num +'.md'), title='Simulation overview')

mdFile.new_paragraph("This is a markdown file created using mdutils python package. This file gives an overview of the"
                     "scenario and the changes in the energy model." 
                     "\n**IMPORTANT:** This file is automatically generated at the end of the simulation. "
                     "Key points from the analyis of the simulation must be added manually.")
mdFile.new_paragraph("**OEMOF.solph version:** 0.5.2 \n"
                     "**Simulation Year:** " + YEAR + "\n"
                     "**Variation:** " + model_ID + "\n"
                     "**Scenario_num:** " + scenario_num)


mdFile.new_header(level=1, title= 'Model ID : ' + str(permutation) + '_' +scenario_num)

mdFile.new_paragraph("**Hypothese**: ")
mdFile.new_line(hypothese) 
mdFile.new_paragraph("**Simulation remarks/changes**: ")
mdFile.new_line(sim_remarks)


mdFile.new_header(2, "Plots: ")

image_text = "electricity_loadprofile"
path = os.path.join(img_PATH, image_text+'_Heatmap.png')
mdFile.new_header(3, image_text)
mdFile.new_paragraph(Html.image(path=path, size='900x600'))
mdFile.new_line()

image_text = "Leistung_Erneuerbare"
path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
mdFile.new_header(3, image_text)
mdFile.new_paragraph(Html.image(path=path, size='400'))
mdFile.new_line()

image_text = "PtX-Technologien"
path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
mdFile.new_header(3, image_text)
mdFile.new_paragraph(Html.image(path=path, size='400'))
mdFile.new_line()

image_text = "Speicherkapazitäten"
path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
mdFile.new_header(3, image_text)
mdFile.new_paragraph(Html.image(path=path, size='400'))
mdFile.new_line()


mdFile.create_md_file()
       








