# -*- coding: utf-8 -*-
"""
Created on Wed Dec  4 16:39:29 2024

@author: rbala
"""

from mdutils.mdutils import MdUtils
from mdutils import Html
import os



def create_simulation_doc(permutation, scenario_num, hypothese, sim_remarks,csv):

    md_PATH = os.path.abspath(os.path.join(os.getcwd(), "docs", "scenario"))
    img_PATH = os.path.abspath(os.path.join(os.getcwd(), "figures", str(permutation)))
    YEAR, model_ID = permutation.split("_")

           
    mdFile = MdUtils(file_name=  os.path.join(md_PATH, str(permutation) + '_' +scenario_num +'.md'), title='Simulation overview')

    mdFile.new_paragraph("This is a markdown file created using mdutils python package. This file gives an overview of the"
                         "scenario and the changes in the energy model." 
                         "\n**IMPORTANT:** This file is automatically generated at the end of the simulation. "
                         "Key points from the analyis of the simulation must be added manually.")
    mdFile.new_paragraph("**OEMOF.solph version:** 0.5.2 \n"
                         "**Simulation Year:** " + YEAR + "\n"
                         "**Variation:** " + model_ID + "\n"
                         "**Scenario_num:** " + scenario_num)


    mdFile.new_header(level=1, title= 'Model ID : ' + str(permutation) + '_' +scenario_num)

    mdFile.new_paragraph("**Hypothese**: ")
    mdFile.new_line(hypothese) 
    mdFile.new_paragraph("**Simulation remarks/changes**: ")
    mdFile.new_line(sim_remarks)


    mdFile.new_header(2, "Plots: ")

    image_text = "electricity_loadprofile"
    path = os.path.join(img_PATH, image_text+'_Heatmap.png')
    mdFile.new_header(3, image_text)
    mdFile.new_paragraph(Html.image(path=path, size='900x600'))
    mdFile.new_line()

    image_text = "Leistung_Erneuerbare"
    path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
    mdFile.new_header(3, image_text)
    mdFile.new_paragraph(Html.image(path=path, size='400'))
    mdFile.new_line()

    image_text = "PtX-Technologien"
    path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
    mdFile.new_header(3, image_text)
    mdFile.new_paragraph(Html.image(path=path, size='400'))
    mdFile.new_line()

    image_text = "Speicherkapazitäten"
    path = os.path.join(img_PATH, scenario_num +'_' + image_text +'.png')
    mdFile.new_header(3, image_text)
    mdFile.new_paragraph(Html.image(path=path, size='400'))
    mdFile.new_line()


    return mdFile.create_md_file()