# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Coverage Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install cbc
      run: |
        sudo apt-get install -y coinor-cbc coinor-libcbc-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Coverage Report
      run: |
        bash tests.sh
        coverage xml
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./coverage.xml